app = "docverterz" # Replace with your Fly.io app name

kill_signal = "SIGINT"
kill_timeout = 5

[build]
  builder = "heroku/ruby"  # Use the appropriate builder

[env]
  PATH = "bin:/app/bin:/app/jruby/bin:/usr/bin:/bin:/app/calibre/bin"
  LD_LIBRARY_PATH = "/app/calibre/lib"
  # Add any other environment variables your app needs

# Define the processes your app will run
[processes]
  web = "gem install foreman; foreman start;" # Replace with the command to start your app, e.g., "bundle exec ruby app.rb"

[[services]]
  http_checks = []
  processes = ["web"]

  [[services.ports]]
    handlers = ["http"]
    port = "8080" # Adjust according to your application’s port

  [[services.tcp_checks]]
    interval = 10000
    timeout = 2000
    grace = 10000
    method = "GET"
    path = "/"
    protocol = "tcp"
